name_char_map = {
    "IRON": "I",
    "IRON_PLATE": "R",
    "COPPER": "O",
    "COPPER_PLATE": "E",
    "GEAR": "G",
    "BAR_WINDING": "B",
    "NUT": "N",
    "SILICATE": "L",
    "WAFER": "W",
    "SULFER": "U",
    "MOTOR": "M",
    "BATTERY": "T",
    "SOLAR_PANNEL": "P",
    "ACCUMULATOR": "A",
    "FABRICATOR": "F",
    "DOG": "D",
    "SMELTER": "S",
    "LAZER_CUTTER": "C",
    "EMPTY": ".",
}

char_name_map = {
    "I": "IRON",
    "R": "IRON_PLATE",
    "O": "COPPER",
    "E": "COPPER_PLATE",
    "G": "GEAR",
    "B": "BAR_WINDING",
    "N": "NUT",
    "L": "SILICATE",
    "W": "WAFER",
    "U": "SULFER",
    "M": "MOTOR",
    "T": "BATTERY",
    "P": "SOLAR_PANNEL",
    "A": "ACCUMULATOR",
    "F": "FABRICATOR",
    "D": "DOG",
    "S": "SMELTER",
    "C": "LAZER_CUTTER",
    ".": "EMPTY",
}
